import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Family Feud",
  description: "Generated by Kielo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
