import type { Metadata } from "next";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Family Feud",
  description: "Generated by Kielo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className={poppins.className}>
      <section className="relative flex items-center justify-center w-screen h-screen p-10 bg-gradient-to-r from-amber-200 to-yellow-400">
        {children}
      </section>
    </main>
  );
}
