import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Adding Rounds",
  description: "Generated by Kielo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="relative flex flex-col items-center justify-center w-screen h-screen p-10 bg-gradient-to-r from-blue-200 to-cyan-200">
      {children}
    </section>
  );
}
