import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/providers/QueryProvider";
import SongMPThree from "@/components/song";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Team Score",
  description: "Generated by Kielo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          {children}
          <SongMPThree />
        </QueryProvider>
      </body>
    </html>
  );
}
